### ISSUE TITLE
python 3 compatibility patch

### ISSUE THREAD

**Issue by elliotclee** [Rentlau/WorkFeature#25]
[workfeature-python3.zip](https://github.com/Rentlau/WorkFeature/files/2897469/workfeature-python3.zip)

**Comment by Rentlau** [comment]
thank a lot

**Comment by Rentlau** [comment]
But you gave me the patch for the WorkFeature-WB (workbench) not for the WorkFeature Macro.
For your information the WorkFeature-WB is now fully compatible with py3 and get some improvement in the WorkFeature-WB repository, branch2019_01:
[https://github.com/Rentlau/WorkFeature-WB/tree/release2019_01](url)

**Comment by elliotclee** [comment]
Sorry and sorry. I just made the patch against whatever the add-ons manager
pulled. Maybe FreeCAD 0.18dev needs to be fixed to pull from the right
WorkFeature-WB branch.

**Comment by PavelKalina** [comment]
Hi, 
it does not work with 0.18.0 or 0.19_pre on x64 WIN10
It worked with 0.17

Pavel

**Comment by Rentlau** [comment]
Now it must work with py3 and QT5 FreeCAD version.
Let me know

**Comment by PavelKalina** [comment]
Installed in fresh FreeCAD-0.18.16110.f7dccfa-WIN-x64-installer.exe on WIN10 Ent. 64b ver 1703

Addon manager:
Gitphyton not found. Using standard download instead.
Installed in:
AppData\Roaming\FreeCAD\Mod\workfeature-macro\
AppData\Roaming\FreeCAD\Macro\start_WF.FCMacro (start_WF.FCMacro has size 0)
Afer reboot Macro found in macro menu but:
„Err: cannot load FreeCAD WorkFeature macro path ! Chech the install!“

When content of  workfeature-macro is DIR moved to macro dir. It works.

Thanks!
