### ISSUE TITLE
no atribute get_pointsNames

### ISSUE THREAD

**Issue by macdroid53** [Rentlau/WorkFeature#31]
Attempting to use "Create projected points" icon and no matter what I select I get the following error:
(Points create by work feature, points of a Body, etc.)

`/home/mac/.FreeCAD/Mod/workfeature-macro`

OS: Debian GNU/Linux 10 (buster) (XFCE/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.20.25564 (Git)
Build type: Release
Branch: master
Hash: 619a30b672cc8b289ca63f2b0ee0214ddf3492fc
Python version: 3.7.3
Qt version: 5.11.3
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

**Comment by Rentlau** [comment]
Correction done.
